# GoReleaser configuration for CLI-Note-App
builds:
  - id: cli-notes
    binary: cli-notes
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Skip certain combinations if needed
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: cli-notes
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE*
      - CHANGELOG*
      - docs/*

# Generate checksums for verification
checksum:
  name_template: 'checksums.txt'

# Automatically generate changelog from git commits
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'Merge pull request'
      - 'Merge branch'